[package]
name = "krpc-mars-terraformer"
version = "0.8.0"
authors = ["cahu"]
license = "GPL-3.0"
edition = "2021"

[dependencies]
krpc-mars = { git = "https://github.com/Cahu/krpc-mars" }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
thiserror = "1"
heck = "0.4"
tera = "1"
